### ISSUE TITLE
Crash while "Reading data" - Ubuntu 16.04 (both 32-bit and 64-bit)

### ISSUE THREAD

**Issue by stoupa91** [open-eid/qesteidutil#14]
Hi, the qesteidutil crashes each time it tries to read data out of the eID card. It shows in the status area "Reading data" and after a few seconds it crashes.

Here is my crash dump:
[CrashDump.zip](https://github.com/open-eid/qesteidutil/files/638372/CrashDump.zip)

I've tried to compile the application from the latest source code, but it has exactly the same behaviour as when installed directly from your repository. At least, here I was able to get the backtrace:
[backtrace.txt](https://github.com/open-eid/qesteidutil/files/638377/backtrace.txt)

**Comment by metsma** [comment]
Can you compile with debug symbols cmake -DCMAKE_BUILD_TYPE=Debug and enable APDU log
https://github.com/open-eid/qesteidutil/wiki/DeveloperTips

**Comment by stoupa91** [comment]
Here is the APDU log

[qesteidutil.log.txt](https://github.com/open-eid/qesteidutil/files/639039/qesteidutil.log.txt)

**Comment by metsma** [comment]
Have you tried any other Reader?

**Comment by stoupa91** [comment]
No, I haven't. I don't have any other at hand.

**Comment by metsma** [comment]
Cany you try to update CCID drivers to latest?

**Comment by stoupa91** [comment]
Amazing. I've installed the latest CCID drivers (https://github.com/LudovicRousseau/CCID/releases/tag/ccid-1.4.25) and it indeed works. Thanks a lot for your help!
