### ISSUE TITLE
Updater reading partial certificates due to obsolete size limit

### ISSUE THREAD

**Issue by blakestorm11** [open-eid/qesteidutil#66]
Updater is still using the obsolete size limit of 0x0600 bytes when reading certs, should use the FCI logic like QSmartCard does. The 0x0600 limit must have been enough for the SHA1 to SHA256 update cycle, but current v3.5 cards can have larger certs (the one on the card I'm looking at right now is 0x0695 bytes), which will only get read partially.
https://github.com/open-eid/qesteidutil/blob/f4d9bb38ff48043d0e3095e81ea39e481dc1e8ce/src/Updater.cpp#L485
https://github.com/open-eid/qesteidutil/blob/f4d9bb38ff48043d0e3095e81ea39e481dc1e8ce/src/QSmartCard.cpp#L603

**Comment by metsma** [comment]
Thank you for spotting, seems like all our test cards are with cert size <= 0x0600

**Comment by blakestorm11** [comment]
Glad I could help. I'm just always curious about the nitty-gritty of these things, so I looked into the code a bit.

Now, considering this bug, could you please advise if it's a good idea to wait until a new **qesteidutil** build is released before running the update on a card with >0x0600 byte certs?

I assume that without being able to get the cert, the update process would inevitably fail at some point. I don't have any test cards available to try this out before running the update on the official card, so I'd rather not get the card into a state only a service center visit could fix. I seems to me that depending on implementation details, the process could potentially get too far into the update to be recoverable when the cert failure is discovered. Because of this, I've stopped short of proceeding beyond the confirmation dialog shown after the first PIN1 entry.

In fact I was somewhat surprised that I was able to get that far, because I was expecting that a server session couldn't be established at all without a client cert being provided during the initial handshake; but apparently at least the initial phase of the connection doesn't actually require a client cert. But it obviously would have to be provided at some point, hence my apprehension. I know many people are updating successfully, but I've also seen reports of failures. At this point I have to assume some of these could be caused by this large cert problem which, going by your statement about your test cards, isn't applicable to all v3.5 cards even after the SHA256 upgrade.

**Comment by metsma** [comment]
Release will come shortly, there is another fix pending (today or maybe tomorrow).
