### ISSUE TITLE
Installation in Fedora?

### ISSUE THREAD

**Issue by timbo-lino** [open-eid/qesteidutil#78]
Hi,

is it possible to install the latest version in fedora? Even fedoras latest version has only qesteidutil version 3.12.4.0, released 24.02.2017 in the repositories.

Thanks!

**Comment by metsma** [comment]
You can contact package mainters and help them out https://admin.fedoraproject.org/pkgdb/package/rpms/qesteidutil/

**Comment by Germano0** [comment]
Hi @timbo-lino we are working on bring it back into official Fedora repositories (package has been orphaned for a while)
Meanwhile I created a personal Copr repository with lastest qesteidutil for Fedora 26 (it still does not compile on F27, I have to work on it as soon I have some free time)
https://copr.fedorainfracloud.org/coprs/germano/qesteidutil/builds/

**Comment by timbo-lino** [comment]
Good to hear that you guys are working on it! Keep on going the great work!

Can you drop a message here when the F27 build is ready?

**Comment by timbo-lino** [comment]
Hi Germano,

I tried you copr repo and it works for me. Thanks!

**Comment by Germano0** [comment]
[qdigidoc update](https://bodhi.fedoraproject.org/updates/FEDORA-2018-8d148ceb02)
[qesteidutil update](https://bodhi.fedoraproject.org/updates/FEDORA-2018-54c7a5b01b)
If you login with FAS account (Fedora Account System) and leave karma feedback you will help in pushing the updates into stable repository as soon as possible

**Comment by metsma** [comment]
Package is upstream
https://src.fedoraproject.org/rpms/qesteidutil
