### ISSUE TITLE
Crash using qesteidutil with eID on Arch Linux x86_64

### ISSUE THREAD

**Issue by RaitoBezarius** [open-eid/qesteidutil#8]
Hi there,

I have been encountering a strange problem using qesteidutil with my recently-received eID.
It is showing "Reading data" on the status (while the card is detected and read from pcsc_scan).

Unfortunately, it crashes with a SIGSEGV signal. Here is attached the crash dump, if it can helps you.

Thank you,
Best regards.

[Crash_Dump.zip](https://github.com/open-eid/qesteidutil/files/518241/Crash_Dump.zip)

**Comment by martinpaljak** [comment]
Hi.

Arch Linux is unfortunately not a "supported" platform.

But a crash is nevertheless an allowed outcome, even if compiled yourself. 

Could you please run it via gdb and give a backtrace?

**Comment by RaitoBezarius** [comment]
@martinpaljak I understand that Arch Linux is not a "supported" platform.

But by using either the binary of the Ubuntu repositories or by compiling the latest version of this repository, I get a crash.

I will send you a backtrace ASAP. :)

**Comment by RaitoBezarius** [comment]
Here's what I could fetch for now:

https://gist.github.com/RaitoBezarius/6daa114e36807fe7b9c66eb4c0fd93a8

**Comment by stoupa91** [comment]
Hi, I'm experiencing same behavior on Ubuntu 16.04 (tested on both 32bit and 64bit). "Reading data" is being shown for a while and then the application crashes..
[CrashDump.zip](https://github.com/open-eid/qesteidutil/files/630401/CrashDump.zip)

**Comment by metsma** [comment]
seems similar issue #14, try to update to latest CCID driver

**Comment by RaitoBezarius** [comment]
@metsma Agreed, it solved the issue with reading data. Thank you.
