### ISSUE TITLE
Missing sandbox instructions

### ISSUE THREAD

**Issue by Germano0** [open-eid/qesteidutil#93]
I am a new qesteidutil Fedora co-maintainer.
I have found in Fedora repository https://src.fedoraproject.org/rpms/qesteidutil/tree/master
the file sandbox-compilation.patch. I want to update such file but in qesteidutil wiki I haven't seen any Wiki explaining how to create such patch.

**Comment by metsma** [comment]
This is done by previous maintainer

**Comment by Germano0** [comment]
but https://github.com/open-eid/qesteidutil/wiki page does not contain any info about sandbox compilation

**Comment by metsma** [comment]
https://github.com/open-eid/qesteidutil/wiki/DeveloperTips#building-in-sandboxed-environment

**Comment by Germano0** [comment]
Ah once you get into Wiki page, it was under another button on the right!
