### ISSUE TITLE
Update DeveloperTips

### ISSUE THREAD

**Issue by Germano0** [open-eid/qesteidutil#94]
DeveloperTips wiki page needs an update, concerning lines of code that should be commented or replaced. They are not alligned with lastest code

**Comment by metsma** [comment]
Updated the wiki

**Comment by Germano0** [comment]
There should be an error: the qesteidutil DeveloperTips wiki contains URL to qdigidoc code, not qesteidutil

**Comment by metsma** [comment]
Fixed

**Comment by Germano0** [comment]
> Fixed

No, section https://github.com/open-eid/qesteidutil/wiki/DeveloperTips#building-in-sandboxed-environment
contains URL pointing to https://github.com/open-eid/qt-common code not qesteidutil

**Comment by metsma** [comment]
qt-common is submodule qesteidutil/qdigidoc in common folder
