### ISSUE TITLE
Invalid PUK after updating certificates 

### ISSUE THREAD

**Issue by abitrolly** [open-eid/qesteidutil#96]
I successfully updated my ID card, with only one problem - I don't know my PUK. After new codes were revealed, I wrote them down. Perhaps it took too long - I don't know why, but the next step failed and asked to restart process again. After restarting I tried to write newest codes as fast as possible, but I am sure I checked them double. Then I changed my PIN1 and PIN2 to those from the previous set, but I could not change my PUK. I used two out of three attempts to enter the latest PUK and both times it was wrong. I don't want to risk blocking my card.

**Comment by markus-kullerkup** [comment]
Due to the nature of your issue we suggest to contact our ID support via email: abi@id.ee.
We suggest adding screenshots of your problem in the email attachment
